-- No seed data. onboarding_steps is now per-user owned (RLS: auth.uid() = user_id), so
-- there is no shared, ownerless step list to seed — a row inserted here would have a NULL
-- owner and be invisible to everyone under the policies. Each signed-in user creates their
-- own steps; automated tests seed their own per-user fixtures (see tests/ and supabase/tests/).
